const cleanText = "CERTIFICATE ID TJHR023 INSTITUTE 0F TECHN0L0GY JHARKHAND UP0N THE REC0MMENDATI0N 0F THE SENATE HEREBY C0NFERS THE DEGREE 0F BACHEL0R 0F TECHN0L0GY IN ELECTRICAL ENGINEERING(EE) T0 NIKHIL TIWARI (R0LL N0 R0LL023) WH0 HAS SUCCESSFULLY C0MPLETED THE REQUIREMENTS PRESCRIBED UNDER THE REGULATI0NS F0R THE AWARD 0F THISDEGREE WITH CGPA 0F 8.23 IN THE YEAR 2025. GIVEN THIS DAY 30 FEBRUARY 2025 THIS DEGREEIIS PRESENTED UNDER THE SEAL 0F INSTITUTE AT JHARKHAND IN THE REPUBLIC 0F INDIA. CHAIRMAN REGISTRAR"
const certIdMatch = cleanText.match(/TJHR\d{3}/);
if (!certIdMatch) {
            console.log("Certificate INVALID ❌ (ID not found)");
        }else{
          const certificate_id = "I"+certIdMatch[0];
          console.log(certificate_id)
        }

        aws#is#fuck